version: '3'

includes:
  cli:
    taskfile: ./packages/acrud-cli
    dir: ./packages/acrud-cli

env:
  JWT_SECRET: McI6A9!kEgz81v^%f%vVx8mzKS
  RUST_LOG: debug
  DATABASE_URL: postgres://pguser:pgpass@127.0.0.1:5447/todo_hyper
  SALT: o#596T*O65MATwDX4LtR

tasks:
  mongo:start:
    desc: start mongodb
    cmds:
      - docker-compose up -d && docker-compose logs -f mongo

  start:dev:
    desc: start server in development mod

    cmds:
      - docker-compose up -d
      - cargo-watch -x run

  start:prod:
    desc: start in production mod
    cmds:
      - docker-compose up -d
      -  cargo build --release
      - ./target/release/api

  bench:
    desc: start benchmark thanks to drill
    cmds:
      - drill --benchmark ./drill/benchmark.yml --stats

  check:
    desc: check applications
    cmds:
      - cargo check --all

  test:
    desc: test applications
    cmds:
      - cargo test --all

  lint:
    desc: lint applications
    cmds:
      - cargo clippy --all

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo +nightly fmt --all
