[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]

# internal packages
entity = { path = "entity" }
migration = { path = "migration" }

# external packages
axum = { version = "0.5.9", features = ["headers"] }
sea-orm = { version = "0.8.0", features = ["sqlx-postgres", "runtime-tokio-native-tls"], default-features = false  }
tokio = { version = "1.19.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
hyper = { version = "0.14.19", features = ["full"] }
jsonwebtoken = "8.1.1"
once_cell = "1.12.0"
acrud = { path = "../acrud" }
validator = { version = "0.14", features = ["derive"] }
