[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = "0.8.0"
serde = { version = "1.0.137", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
validator = { version = "0.14", features = ["derive"] }
utoipa = { version = "1.1.0", features = ["uuid"]}
serde_json = "1.0"
rust-argon2 = "1.0"
